### ISSUE TITLE
How to run it?

### ISSUE THREAD

**Issue by hungcuiga1** [vishwakneelamegam/deepspeech-android#1]
Hello @vishwakneelamegam ,Thank you for great project. Can you help me with any question? I don't know how to run it, i downloaded "deepspeech-0.9.3-models.tflite" but don't know where is it putted and where is "org.deepspeech:libdeepspeech:0.9.3" written. Thank you soo much.

**Comment by vishwakneelamegam** [comment]
paste this(deepspeech-0.9.3-models.tflite) in your external storage of android device.
write org.deepspeech:libdeepspeech:0.9.3 in your gradle file of android application.
if you have downloaded my code then you don't need to add org.deepspeech:libdeepspeech:0.9.3.  because i have added
org.deepspeech:libdeepspeech:0.9.3 in gradle file.

**Comment by hungcuiga1** [comment]
Thanks @vishwakneelamegam I think it would be a lot better if it did with data from the microphon

**Comment by vishwakneelamegam** [comment]
yes.  I am also trying it.

**Comment by vishwakneelamegam** [comment]
update me if you do with microphone.

**Comment by hungcuiga1** [comment]
@vishwakneelamegam I don't even have any android knowledge, I just found out @@

**Comment by vishwakneelamegam** [comment]
deepspeech python version is available.  if you want i will make it public.

**Comment by hungcuiga1** [comment]
Thanks you <3

**Comment by vishwakneelamegam** [comment]
https://github.com/vishwakneelamegam/deepspeech-python  deepspeech python code.

**Comment by vishwakneelamegam** [comment]
@hungcuiga1 i am closing this issue if you want to contact me use this(vishwakneelamegam@gmail.com) email id.  have a great day.
